ALTER TABLE merchants ADD COLUMN IF NOT EXISTS krs DOUBLE PRECISION DEFAULT 0;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS cra DOUBLE PRECISION DEFAULT 0;

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS krs DOUBLE PRECISION;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS trs DOUBLE PRECISION;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS cra DOUBLE PRECISION;
