-- ============================================================
-- Hibernate Envers Audit Tables (Backfill)
-- Migration: V120__add_missing_aud_tables.sql
-- Description: Creates the _aud audit mirror tables for the 14
--              @Audited entities that lacked explicit Flyway
--              migrations after ddl-auto was switched from
--              `update` to `validate`. CbkSubmission (V117) and
--              RuleExecutionLog (V119) already have their _aud
--              tables and are intentionally NOT recreated here.
--
-- Tables created (entity -> table):
--   CaseActivity              -> case_activities_aud
--   CaseAlert                 -> case_alerts_aud
--   CaseDecision              -> case_decisions_aud
--   CaseEntity                -> case_entities_aud
--   CaseEvidence              -> case_evidence_aud
--   CaseNote                  -> case_notes_aud
--   CaseQueue                 -> case_queues_aud
--   CaseTransaction           -> case_transactions_aud
--   ComplianceCase            -> compliance_cases_aud
--   ComplianceDeadline        -> compliance_deadlines_aud
--   EscalationRule            -> escalation_rules_aud
--   RuleDefinition            -> rule_definitions_aud
--   SuspiciousActivityReport  -> suspicious_activity_reports_aud
--
--   (RuleExecutionLog has rule_execution_logs_aud in V119 - skipped)
--   (CbkSubmission   has cbk_submissions_aud      in V117 - skipped)
--
-- Plus the shared `revinfo` table (Envers default schema) and
-- the `case_relationships_aud` join-table audit (ComplianceCase
-- declares @Audited on its @ManyToMany relatedCases collection).
--
-- Conventions match V117 / V119:
--   rev      INTEGER NOT NULL  (FK -> revinfo.rev)
--   revtype  SMALLINT
--   PK       (id, rev)
--   All entity columns NULLABLE (Envers history rows are partial).
-- ============================================================

-- ------------------------------------------------------------
-- Shared revision info table (Envers default).
-- Created here because no prior migration defines it; under the
-- previous ddl-auto=update convention Hibernate auto-created it.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS revinfo (
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE INDEX IF NOT EXISTS idx_revinfo_revtstmp
    ON revinfo (revtstmp);

COMMENT ON TABLE revinfo IS 'Hibernate Envers shared revision metadata; one row per transactional revision';

-- ============================================================
-- case_activities_aud  (entity: CaseActivity)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_activities_aud (
    id                  BIGINT      NOT NULL,
    rev                 INTEGER     NOT NULL,
    revtype             SMALLINT,
    case_id             BIGINT,
    activity_type       VARCHAR(255),
    description         TEXT,
    details             TEXT,
    performed_by        BIGINT,
    performed_at        TIMESTAMP,
    related_entity_id   BIGINT,
    related_entity_type VARCHAR(255),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_activities_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_activities_aud_rev
    ON case_activities_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_activities_aud_id
    ON case_activities_aud (id);

-- ============================================================
-- case_alerts_aud  (entity: CaseAlert)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_alerts_aud (
    id              BIGINT      NOT NULL,
    rev             INTEGER     NOT NULL,
    revtype         SMALLINT,
    case_id         BIGINT,
    alert_type      VARCHAR(255),
    rule_name       VARCHAR(255),
    rule_id         VARCHAR(255),
    model_version   VARCHAR(255),
    rule_version    VARCHAR(255),
    score           DOUBLE PRECISION,
    description     TEXT,
    raw_data        TEXT,
    triggered_at    TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_alerts_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_alerts_aud_rev
    ON case_alerts_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_alerts_aud_id
    ON case_alerts_aud (id);

-- ============================================================
-- case_decisions_aud  (entity: CaseDecision)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_decisions_aud (
    id            BIGINT      NOT NULL,
    rev           INTEGER     NOT NULL,
    revtype       SMALLINT,
    case_id       BIGINT,
    decision_type VARCHAR(255),
    justification TEXT,
    decided_by    BIGINT,
    decided_at    TIMESTAMP,
    is_final      BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_decisions_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_decisions_aud_rev
    ON case_decisions_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_decisions_aud_id
    ON case_decisions_aud (id);

-- ============================================================
-- case_entities_aud  (entity: CaseEntity)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_entities_aud (
    id               BIGINT      NOT NULL,
    rev              INTEGER     NOT NULL,
    revtype          SMALLINT,
    case_id          BIGINT,
    entity_type      VARCHAR(255),
    entity_reference VARCHAR(255),
    description      TEXT,
    linked_at        TIMESTAMP,
    linked_by        BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_entities_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_entities_aud_rev
    ON case_entities_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_entities_aud_id
    ON case_entities_aud (id);

-- ============================================================
-- case_evidence_aud  (entity: CaseEvidence)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_evidence_aud (
    id              BIGINT      NOT NULL,
    rev             INTEGER     NOT NULL,
    revtype         SMALLINT,
    case_id         BIGINT,
    uploaded_by_id  BIGINT,
    file_name       VARCHAR(500),
    file_type       VARCHAR(100),
    storage_path    VARCHAR(1024),
    description     TEXT,
    uploaded_at     TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_evidence_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_evidence_aud_rev
    ON case_evidence_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_evidence_aud_id
    ON case_evidence_aud (id);

-- ============================================================
-- case_notes_aud  (entity: CaseNote)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_notes_aud (
    id          BIGINT      NOT NULL,
    rev         INTEGER     NOT NULL,
    revtype     SMALLINT,
    case_id     BIGINT,
    author_id   BIGINT,
    content     TEXT,
    internal    BOOLEAN,
    created_at  TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_notes_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_notes_aud_rev
    ON case_notes_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_notes_aud_id
    ON case_notes_aud (id);

-- ============================================================
-- case_queues_aud  (entity: CaseQueue)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_queues_aud (
    id              BIGINT      NOT NULL,
    rev             INTEGER     NOT NULL,
    revtype         SMALLINT,
    queue_name      VARCHAR(255),
    target_role     VARCHAR(255),
    min_priority    VARCHAR(32),
    max_queue_size  INTEGER,
    auto_assign     BOOLEAN,
    enabled         BOOLEAN,
    created_at      TIMESTAMP,
    description     TEXT,
    psp_id          BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_queues_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_queues_aud_rev
    ON case_queues_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_queues_aud_id
    ON case_queues_aud (id);

-- ============================================================
-- case_transactions_aud  (entity: CaseTransaction)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_transactions_aud (
    id                BIGINT      NOT NULL,
    rev               INTEGER     NOT NULL,
    revtype           SMALLINT,
    case_id           BIGINT,
    transaction_id    BIGINT,
    relationship_type VARCHAR(255),
    added_at          TIMESTAMP,
    added_by          BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_case_transactions_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_transactions_aud_rev
    ON case_transactions_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_transactions_aud_id
    ON case_transactions_aud (id);

-- ============================================================
-- compliance_cases_aud  (entity: ComplianceCase)
-- Audited columns mirror compliance_cases as defined by V2 +
-- subsequent migrations (psp_id, queue_id, archive_*).
-- merchant_id is BIGINT here (V100 fixed up legacy VARCHAR rows).
-- ============================================================
CREATE TABLE IF NOT EXISTS compliance_cases_aud (
    id                    BIGINT      NOT NULL,
    rev                   INTEGER     NOT NULL,
    revtype               SMALLINT,
    case_reference        TEXT,
    merchant_id           BIGINT,
    psp_id                BIGINT,
    description           TEXT,
    status                VARCHAR(32),
    priority              VARCHAR(32),
    sla_deadline          TIMESTAMP,
    days_open             INTEGER,
    assigned_to_user_id   BIGINT,
    assigned_by_user_id   BIGINT,
    assigned_at           TIMESTAMP,
    escalated             BOOLEAN,
    escalated_to_user_id  BIGINT,
    escalation_reason     VARCHAR(1024),
    escalated_at          TIMESTAMP,
    queue_id              BIGINT,
    resolution            VARCHAR(255),
    resolution_notes      TEXT,
    resolved_by           BIGINT,
    resolved_at           TIMESTAMP,
    created_at            TIMESTAMP,
    updated_at            TIMESTAMP,
    archived              BOOLEAN,
    archived_at           TIMESTAMP,
    archive_reference     VARCHAR(1024),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_compliance_cases_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_compliance_cases_aud_rev
    ON compliance_cases_aud (rev);
CREATE INDEX IF NOT EXISTS idx_compliance_cases_aud_id
    ON compliance_cases_aud (id);

-- ============================================================
-- case_relationships_aud  (audit of @ManyToMany join-table
-- declared on ComplianceCase.relatedCases with @Audited)
-- ============================================================
CREATE TABLE IF NOT EXISTS case_relationships_aud (
    rev             INTEGER NOT NULL,
    revtype         SMALLINT,
    case_id         BIGINT  NOT NULL,
    related_case_id BIGINT  NOT NULL,
    PRIMARY KEY (rev, case_id, related_case_id),
    CONSTRAINT fk_case_relationships_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_case_relationships_aud_rev
    ON case_relationships_aud (rev);
CREATE INDEX IF NOT EXISTS idx_case_relationships_aud_case
    ON case_relationships_aud (case_id);

-- ============================================================
-- compliance_deadlines_aud  (entity: ComplianceDeadline)
-- V118 already ALTERed this table to add psp_id; we create the
-- definitive baseline here. The ALTER in V118 was an
-- IF-NOT-EXISTS no-op on the column; this CREATE TABLE
-- IF NOT EXISTS is also a no-op if Hibernate had already
-- materialised the table under ddl-auto=update.
-- ============================================================
CREATE TABLE IF NOT EXISTS compliance_deadlines_aud (
    id             BIGINT       NOT NULL,
    rev            INTEGER      NOT NULL,
    revtype        SMALLINT,
    deadline_type  VARCHAR(255),
    deadline_date  TIMESTAMP,
    description    TEXT,
    jurisdiction   VARCHAR(255),
    psp_id         BIGINT,
    completed      BOOLEAN,
    completed_at   TIMESTAMP,
    created_at     TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_compliance_deadlines_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_compliance_deadlines_aud_rev
    ON compliance_deadlines_aud (rev);
CREATE INDEX IF NOT EXISTS idx_compliance_deadlines_aud_id
    ON compliance_deadlines_aud (id);

-- ============================================================
-- escalation_rules_aud  (entity: EscalationRule)
-- ============================================================
CREATE TABLE IF NOT EXISTS escalation_rules_aud (
    id                    BIGINT         NOT NULL,
    rev                   INTEGER        NOT NULL,
    revtype               SMALLINT,
    rule_name             VARCHAR(255),
    enabled               BOOLEAN,
    min_priority          VARCHAR(32),
    min_risk_score        DOUBLE PRECISION,
    min_amount            NUMERIC(19,2),
    days_open             INTEGER,
    escalate_to_role      VARCHAR(255),
    escalate_to_user_id   BIGINT,
    reason_template       TEXT,
    created_at            TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_escalation_rules_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_escalation_rules_aud_rev
    ON escalation_rules_aud (rev);
CREATE INDEX IF NOT EXISTS idx_escalation_rules_aud_id
    ON escalation_rules_aud (id);

-- ============================================================
-- rule_definitions_aud  (entity: RuleDefinition)
-- Mirrors rule_definitions (V116). Note: Envers does not
-- enforce UNIQUE on history rows.
-- ============================================================
CREATE TABLE IF NOT EXISTS rule_definitions_aud (
    id              BIGINT      NOT NULL,
    rev             INTEGER     NOT NULL,
    revtype         SMALLINT,
    name            VARCHAR(255),
    description     VARCHAR(255),
    rule_json       TEXT,
    drl_content     TEXT,
    rule_type       VARCHAR(50),
    rule_expression TEXT,
    score_impact    INTEGER,
    action_type     VARCHAR(50),
    priority        INTEGER,
    enabled         BOOLEAN,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    psp_id          BIGINT,
    created_by      BIGINT,
    updated_by      BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_rule_definitions_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_rule_definitions_aud_rev
    ON rule_definitions_aud (rev);
CREATE INDEX IF NOT EXISTS idx_rule_definitions_aud_id
    ON rule_definitions_aud (id);

-- ============================================================
-- suspicious_activity_reports_aud  (entity: SuspiciousActivityReport)
-- Mirrors suspicious_activity_reports (V4) plus psp_id (V111).
-- @ManyToMany sar_transactions has NOT_AUDITED relation target,
-- so no sar_transactions_aud join-table is generated.
-- ============================================================
CREATE TABLE IF NOT EXISTS suspicious_activity_reports_aud (
    id                          BIGINT          NOT NULL,
    rev                         INTEGER         NOT NULL,
    revtype                     SMALLINT,
    sar_reference               TEXT,
    psp_id                      BIGINT,
    status                      VARCHAR(32),
    created_by_user_id          BIGINT,
    reviewed_by_user_id         BIGINT,
    approved_by_user_id         BIGINT,
    approved_at                 TIMESTAMP,
    filing_reference_number     VARCHAR(255),
    filed_at                    TIMESTAMP,
    filed_by_user_id            BIGINT,
    filing_receipt              TEXT,
    sar_type                    VARCHAR(32),
    jurisdiction                VARCHAR(255),
    filing_deadline             TIMESTAMP,
    suspicious_activity_type    VARCHAR(255),
    narrative                   TEXT,
    total_suspicious_amount     NUMERIC(19,2),
    case_id                     BIGINT,
    amends_sar_id               BIGINT,
    amendment_reason            VARCHAR(1024),
    created_at                  TIMESTAMP,
    updated_at                  TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_suspicious_activity_reports_aud_rev
        FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_suspicious_activity_reports_aud_rev
    ON suspicious_activity_reports_aud (rev);
CREATE INDEX IF NOT EXISTS idx_suspicious_activity_reports_aud_id
    ON suspicious_activity_reports_aud (id);

-- ============================================================
-- End of V120
-- ============================================================
