UPDATE country_risk_scores
   SET fatf_listed = FALSE,
       fatf_status = NULL,
       last_reviewed_at = CURRENT_TIMESTAMP,
       updated_at = CURRENT_TIMESTAMP
 WHERE fatf_listed = TRUE;

INSERT INTO country_risk_scores (
    country_code, country_name, risk_score, risk_tier, fatf_listed,
    fatf_status, last_reviewed_at, source, updated_at
)
VALUES
    ('IR', 'Iran', 95, 'VERY_HIGH', TRUE, 'BLACKLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('KP', 'North Korea', 98, 'VERY_HIGH', TRUE, 'BLACKLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('MM', 'Myanmar', 92, 'VERY_HIGH', TRUE, 'BLACKLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('DZ', 'Algeria', 70, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('AO', 'Angola', 72, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('BO', 'Bolivia', 68, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('BG', 'Bulgaria', 70, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('CM', 'Cameroon', 72, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('CI', 'Cote d''Ivoire', 70, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('CD', 'Democratic Republic of the Congo', 78, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('HT', 'Haiti', 80, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('KE', 'Kenya', 68, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('KW', 'Kuwait', 65, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('LA', 'Laos', 75, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('LB', 'Lebanon', 78, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('MC', 'Monaco', 65, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('NA', 'Namibia', 70, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('NP', 'Nepal', 68, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('PG', 'Papua New Guinea', 72, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('SS', 'South Sudan', 82, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('SY', 'Syria', 90, 'VERY_HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('VE', 'Venezuela', 80, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('VN', 'Vietnam', 68, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('VG', 'British Virgin Islands', 68, 'HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP),
    ('YE', 'Yemen', 85, 'VERY_HIGH', TRUE, 'GREYLIST', CURRENT_TIMESTAMP, 'FATF_FEB_2026', CURRENT_TIMESTAMP)
ON CONFLICT (country_code) DO UPDATE
SET country_name = EXCLUDED.country_name,
    risk_score = EXCLUDED.risk_score,
    risk_tier = EXCLUDED.risk_tier,
    fatf_listed = EXCLUDED.fatf_listed,
    fatf_status = EXCLUDED.fatf_status,
    last_reviewed_at = EXCLUDED.last_reviewed_at,
    source = EXCLUDED.source,
    updated_at = EXCLUDED.updated_at;
