ALTER TABLE psps
ADD COLUMN IF NOT EXISTS accent_color VARCHAR(20),
ADD COLUMN IF NOT EXISTS font_family VARCHAR(100),
ADD COLUMN IF NOT EXISTS font_size VARCHAR(20),
ADD COLUMN IF NOT EXISTS button_radius VARCHAR(20),
ADD COLUMN IF NOT EXISTS button_style VARCHAR(50),
ADD COLUMN IF NOT EXISTS nav_style VARCHAR(50);


