server:
  port: 8091

spring:
  application:
    name: hokeka-aml-microservice

aerospike:
  host: ${AEROSPIKE_HOST:fd-test-aerospike}
  port: ${AEROSPIKE_PORT:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
